### ISSUE TITLE
Ajout d'une personne au recensement

### ISSUE THREAD

**Issue by mlebrun40** [Listenbourg/Recensement#1]
Bonjour je voudrais demander à rajouter @LesMediatheques sur Twitter c'est le seul compte et compte officiel qui gère l'administration et les évènements au sein du pays si besoin d'en discuter vous pouvez me contacter par Twitter ou bien au 0767956467

**Comment by niixxlegacy** [comment]
T'es au courant que ce que tu met ici est public ?

**Comment by TathanDev** [comment]
Enlève ton numéro de téléphone x)

**Comment by mlebrun40** [comment]
Oui je suis au courant 😅 et le téléphone t'inquiète c'est mon second téléphone que j'ai d'ailleurs il y a le même numéro sur mon site

**Comment by maelbecel** [comment]
Merge
